---
- name: Update APT cache
  apt:
    update_cache: true

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy index file to remote hosts
  ansible.builtin.copy:
    src: ../files/ansible-index.html
    dest: /var/www/html/ansible-index.html

- name: Copy Nginx configuration file to remote hosts
  ansible.builtin.copy:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: nginx
